import { defineConfig } from "vite-plus";

const ignorePatterns = [
  "**/coverage",
  "**/dist",
  "**/node_modules",
  "**/pnpm-lock.yaml",
  "**/routeTree.gen.ts",
  ".agent/**",
  ".agents/**",
  ".claude/**",
  ".codex/**",
  ".continue/**",
  ".cursor/**",
  ".gemini/**",
  ".opencode/**",
  ".pi/**",
  ".roo/**",
  ".windsurf/**",
  "tools/oxlint/anti-slop/**",
];

export default defineConfig({
  fmt: {
    arrowParens: "always",
    bracketSameLine: false,
    bracketSpacing: true,
    endOfLine: "lf",
    ignorePatterns,
    jsxSingleQuote: false,
    printWidth: 80,
    proseWrap: "never",
    quoteProps: "as-needed",
    semi: true,
    singleQuote: false,
    sortImports: { ignoreCase: true, newlinesBetween: true, order: "asc" },
    sortPackageJson: true,
    tabWidth: 2,
    trailingComma: "es5",
    useTabs: false,
  },
  lint: {
    ignorePatterns,
    jsPlugins: [
      { name: "vite-plus", specifier: "vite-plus/oxlint-plugin" },
      { name: "anti-slop", specifier: "./tools/oxlint/anti-slop/index.ts" },
    ],
    options: { typeAware: true, typeCheck: true },
    overrides: [
      {
        files: ["packages/*/test/**/*.ts"],
        rules: { "promise/prefer-await-to-then": "off" },
      },
      {
        files: ["apps/docs/vite.config.ts"],
        // `@stylexjs/unplugin/vite` is typed as returning `any`; its typed factory skips the Vite hooks that emit CSS.
        rules: { "typescript/no-unsafe-return": "off" },
      },
    ],
    plugins: ["eslint", "typescript", "oxc", "promise", "jsdoc"],
    rules: {
      "anti-slop/no-array-filter-map": "error",
      "anti-slop/no-chained-type-assertions": "error",
      "anti-slop/no-conditional-empty-object-spread": "error",
      "anti-slop/no-known-value-widening": "error",
      "anti-slop/no-module-mocking": "error",
      "anti-slop/no-object-parameters": "error",
      "anti-slop/no-reduce-accumulator-copy": "error",
      "anti-slop/no-reflect-apply": "error",
      "anti-slop/no-reflect-get": "error",
      "anti-slop/no-runtime-typeof": "error",
      "anti-slop/no-shape-in-symbol-names": "error",
      "anti-slop/no-unknown-parameters": "error",
      "anti-slop/no-unknown-returns": "error",
      "anti-slop/no-unknown-type-aliases": "error",
      "anti-slop/no-unsafe-dictionary-type": "error",
      "anti-slop/no-widen-then-assert": "error",
      "anti-slop/require-readable-spacing": "error",
      "anti-slop/require-safety-comment-for-type-assertion": "error",
      complexity: "error",
      eqeqeq: "error",
      // Anti-slop wins conflicts: without `typeof`, primitives are told apart by boxing them.
      "eslint/no-constant-binary-expression": "off",
      "func-style": ["error", "declaration", { allowArrowFunctions: false }],
      // The docs site renders TSDoc, whose `@remarks` isn't a JSDoc tag.
      "jsdoc/check-tag-names": ["warn", { definedTags: ["remarks"] }],
      "jsdoc/empty-tags": "error",
      "no-multi-assign": "error",
      "no-unused-vars": "error",
      "no-use-before-define": ["error", { functions: false }],
      "oxc/no-accumulating-spread": "error",
      "promise/prefer-await-to-callbacks": "error",
      "promise/prefer-await-to-then": "error",
      "require-await": "error",
      "typescript/await-thenable": "error",
      "typescript/consistent-type-imports": "error",
      "typescript/no-deprecated": "error",
      "typescript/no-explicit-any": "error",
      "typescript/no-extraneous-class": "error",
      "typescript/no-floating-promises": "error",
      "typescript/no-misused-promises": "error",
      "typescript/no-non-null-assertion": "error",
      "typescript/no-unsafe-argument": "error",
      "typescript/no-unsafe-assignment": "error",
      "typescript/no-unsafe-call": "error",
      "typescript/no-unsafe-member-access": "error",
      "typescript/no-unsafe-return": "error",
      "typescript/no-unsafe-type-assertion": "error",
      "typescript/strict-boolean-expressions": "error",
      "vite-plus/prefer-vite-plus-imports": "error",
    },
  },
  run: { cache: true },
});
