import { PluginError } from "./plugin-error";

/** `tomekit/content` was imported without the `tomekit()` Vite plugin or `tomekit/register`. */
class MissingPluginError extends PluginError {
  override name = "MissingPluginError";

  constructor() {
    super(
      "tomekit/content is generated by the tomekit() Vite plugin. Add it to the plugins in your Vite config, or outside Vite run Node with --import tomekit/register."
    );
  }
}

export { MissingPluginError };
