import { PluginError } from "./plugin-error";

/** `tomekit/content` or `tomekit/content-modules` was imported without the `tomekit()` Vite plugin or `tomekit/register`. */
class MissingPluginError extends PluginError {
  override name = "MissingPluginError";

  /** `module` is the specifier that was imported, eg `tomekit/content`. */
  constructor(module: string) {
    super(
      `${module} is generated by the tomekit() Vite plugin. Add it to the plugins in your Vite config, or outside Vite run Node with --import tomekit/register.`
    );
  }
}

export { MissingPluginError };
