import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const HEADER = "// Generated by tomekit. Do not edit.";

interface GeneratedCollection {
  name: string;
  slugs: readonly string[];
}

function importPath(from: string, to: string): string {
  const relative = path
    .relative(from, to)
    .split(path.sep)
    .join("/")
    .replace(/\.[cm]?[jt]s$/u, "");

  return relative.startsWith(".") ? relative : `./${relative}`;
}

function union(values: readonly string[]): string {
  return values.length === 0
    ? "never"
    : values.map((value) => JSON.stringify(value)).join(" | ");
}

function typesFile(
  collections: readonly GeneratedCollection[],
  configImport: string
): string {
  const slugs = collections
    .map(
      ({ name, slugs: names }) => `  ${JSON.stringify(name)}: ${union(names)};`
    )
    .join("\n");

  return `${HEADER}
import type { Collection as _Collection, InferDocument as _InferDocument, LookupKey as _LookupKey, WithReferences as _WithReferences, WithSlug as _WithSlug } from "tomekit";
import type config from ${JSON.stringify(configImport)};

type _Configs = (typeof config)["collections"];

type _References = NonNullable<(typeof config)["references"]>;

interface _Slugs {
${slugs}
}

/** The name of any collection. */
export type CollectionName = ${union(collections.map(({ name }) => name))};

/** A slug in the named collection, or in any collection, eg \`SlugOf<"posts">\`. */
export type SlugOf<TName extends CollectionName = CollectionName> = _Slugs[TName];

/**
 * A document in the named collection, or in any collection, eg \`DocumentOf<"posts">\`.
 *
 * @typeError A field that doesn't exist on \`metadata\`.
 */
export type DocumentOf<TName extends CollectionName = CollectionName> = {
  [TKey in TName]: _WithSlug<_WithReferences<_InferDocument<_Configs[TKey & keyof _Configs]>, TKey extends keyof _References ? _References[TKey] : Record<never, never>, _Slugs>, SlugOf<TKey>>;
}[TName];

// No known slugs for a union of names: a slug may exist in only one of them.
type _KnownSlug<TName extends CollectionName, TEach extends CollectionName = TName> = TEach extends unknown ? ([TName] extends [TEach] ? SlugOf<TName> : never) : never;

/**
 * Every collection in your config.
 *
 * @typeError A collection name that isn't in the config, eg \`collections.get("postz")\`.
 */
export declare const collections: {
  /** The collection with this name. */
  get<TName extends CollectionName>(this: void, name: TName): _Collection<DocumentOf<TName>, SlugOf<TName>, _KnownSlug<TName>>;
  /** The collection with this name, or \`undefined\` if there is none, eg for a route param. */
  get<TKey extends string>(this: void, name: _LookupKey<TKey, CollectionName>): _Collection<DocumentOf, SlugOf> | undefined;
  /** Whether a collection has this name. Narrows a route param to \`CollectionName\`. */
  has(this: void, name: string): name is CollectionName;
  /** Every collection name, in config order. */
  names(this: void): readonly CollectionName[];
};
`;
}

/**
 * Writes the types for `tomekit/content` to `<directory>/content.d.ts`, only
 * when they changed, so TypeScript does not reload for nothing. Returns
 * whether the file was written.
 */
async function writeTypes(
  directory: string,
  configPath: string,
  collections: readonly GeneratedCollection[]
): Promise<boolean> {
  await mkdir(directory, { recursive: true });
  const file = path.join(directory, "content.d.ts");
  const types = typesFile(collections, importPath(directory, configPath));
  const current = await readFile(file, "utf-8").catch(() => null);

  if (current === types) {
    return false;
  }

  await writeFile(file, types);

  return true;
}

export { type GeneratedCollection, writeTypes };
