import { randomUUID } from "node:crypto";
import { mkdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";

import { createImportModule } from "./import-module";
import { createCollection, createCollections } from "./query";
import { listSource, PURE } from "./serialize";
import type { Serialized } from "./serialize";

const HEADER = "// Generated by tomekit. Do not edit.";

interface GeneratedCollection {
  name: string;
  slugs: readonly string[];
}

interface ModuleCollection {
  name: string;
  serialized: readonly Serialized[];
}

function importPath(from: string, to: string): string {
  const relative = path
    .relative(from, to)
    .split(path.sep)
    .join("/")
    .replace(/\.[cm]?[jt]s$/u, "");

  return relative.startsWith(".") ? relative : `./${relative}`;
}

function union(values: readonly string[]): string {
  return values.length === 0
    ? "never"
    : values.map((value) => JSON.stringify(value)).join(" | ");
}

function typesFile(
  collections: readonly GeneratedCollection[],
  configImport: string
): string {
  const slugs = collections
    .map(
      ({ name, slugs: names }) => `  ${JSON.stringify(name)}: ${union(names)};`
    )
    .join("\n");

  return `${HEADER}
import type { Collection as _Collection, InferDocument as _InferDocument, LookupKey as _LookupKey, WithReferences as _WithReferences, WithSlug as _WithSlug } from "tomekit";
import type config from ${JSON.stringify(configImport)};

type _Configs = (typeof config)["collections"];

type _References = NonNullable<(typeof config)["references"]>;

interface _Slugs {
${slugs}
}

/** The name of any collection. */
export type CollectionName = ${union(collections.map(({ name }) => name))};

/** A slug in the named collection, or in any collection, eg \`SlugOf<"posts">\`. */
export type SlugOf<TName extends CollectionName = CollectionName> = _Slugs[TName];

/** A document in the named collection, or in any collection, eg \`DocumentOf<"posts">\`. */
export type DocumentOf<TName extends CollectionName = CollectionName> = {
  [TKey in TName]: _WithSlug<_WithReferences<_InferDocument<_Configs[TKey & keyof _Configs]>, TKey extends keyof _References ? _References[TKey] : Record<never, never>, _Slugs>, SlugOf<TKey>>;
}[TName];

// No known slugs for a union of names: a slug may exist in only one of them.
type _KnownSlug<TName extends CollectionName, TEach extends CollectionName = TName> = TEach extends unknown ? ([TName] extends [TEach] ? SlugOf<TName> : never) : never;

${collections
  .map(
    ({ name }) => `/** The \`${name}\` collection. */
export declare const ${name}: _Collection<DocumentOf<${JSON.stringify(name)}>, SlugOf<${JSON.stringify(name)}>, SlugOf<${JSON.stringify(name)}>>;
`
  )
  .join("\n")}
/** Every collection in your config, for a name only known at runtime, eg a route param. Import a collection by name otherwise. */
export declare const collections: {
  /** The collection with this name. */
  get<TName extends CollectionName>(this: void, name: TName): _Collection<DocumentOf<TName>, SlugOf<TName>, _KnownSlug<TName>>;
  /** The collection with this name, or \`undefined\` if there is none, eg for a route param. */
  get<TKey extends string>(this: void, name: _LookupKey<TKey, CollectionName>): _Collection<DocumentOf, SlugOf> | undefined;
  /** Whether a collection has this name. Narrows a route param to \`CollectionName\`. */
  has(this: void, name: string): name is CollectionName;
  /** Every collection name, in config order. */
  names(this: void): readonly CollectionName[];
};
`;
}

/**
 * The `tomekit/content` module: one export per collection, so a bundle keeps
 * only the collections it imports, and `collections` for names known at
 * runtime.
 */
function contentModule(collections: readonly ModuleCollection[]): string {
  const exports = collections.map(
    ({ name, serialized }) =>
      `export const ${name} = ${PURE}_createCollection(${listSource(serialized)});`
  );

  const names = collections.map(({ name }) => name).join(",");

  // The runtime is inlined, so the file imports nothing and runs wherever it is copied or cached.
  // Aliased with "_", which no collection name starts with, so a collection can't shadow it.
  return `${HEADER}
const _createCollection = ${createCollection.toString()};
const _createCollections = ${createCollections.toString()};
${exports.join("\n")}
export const collections = ${PURE}_createCollections({${names}});
`;
}

/**
 * The `tomekit/content-modules` module: a lazy import per module path, so a
 * bundler splits each module into its own chunk and a page loads only its
 * own. `modules` are relative to the root, which is `directory`'s parent.
 */
function modulesModule(modules: readonly string[]): string {
  const importers = modules.map(
    (module) =>
      `[${JSON.stringify(module)},() => import(${JSON.stringify(`../${module}`)})]`
  );

  return `${HEADER}
const _createImportModule = ${createImportModule.toString()};
export const importModule = ${PURE}_createImportModule(new Map([${importers.join(",")}]));
`;
}

const MODULES_TYPES = `${HEADER}
import type { Module as _Module } from "tomekit";

/** Imports a document's module body, eg a compiled MDX file. Only the pages that call it load the module. */
export declare function importModule<TExports>(module: _Module<TExports>): Promise<TExports>;
`;

/** Writes `text` only when it differs from the file, through a temporary file, so a reader never sees half of it. Returns whether it wrote. */
async function writeChanged(file: string, text: string): Promise<boolean> {
  const current = await readFile(file, "utf-8").catch(() => null);

  if (current === text) {
    return false;
  }

  await replaceFile(file, text);

  return true;
}

/** Writes through a temporary file and `rename`, so a reader never sees half a file. */
async function replaceFile(file: string, text: string): Promise<void> {
  await mkdir(path.dirname(file), { recursive: true });
  const temporary = `${file}.${randomUUID()}.tmp`;

  try {
    await writeFile(temporary, text);
    await rename(temporary, file);
  } finally {
    await rm(temporary, { force: true });
  }
}

/**
 * Writes the types for `tomekit/content` to `<directory>/content.d.ts`, only
 * when they changed, so TypeScript does not reload for nothing. Returns
 * whether the file was written.
 */
async function writeTypes(
  directory: string,
  configPath: string,
  collections: readonly GeneratedCollection[]
): Promise<boolean> {
  return await writeChanged(
    path.join(directory, "content.d.ts"),
    typesFile(collections, importPath(directory, configPath))
  );
}

/** Writes the `tomekit/content` module to `<directory>/content.js`, for code that runs outside Vite. Returns whether the file was written. */
async function writeModule(directory: string, code: string): Promise<boolean> {
  return await writeChanged(path.join(directory, "content.js"), code);
}

/** Writes `tomekit/content-modules` and its types to `<directory>/content-modules.js` and `.d.ts`. */
async function writeModules(
  directory: string,
  modules: readonly string[]
): Promise<void> {
  await Promise.all([
    writeChanged(
      path.join(directory, "content-modules.js"),
      modulesModule(modules)
    ),
    writeChanged(path.join(directory, "content-modules.d.ts"), MODULES_TYPES),
  ]);
}

export {
  contentModule,
  type GeneratedCollection,
  type ModuleCollection,
  modulesModule,
  replaceFile,
  writeModule,
  writeModules,
  writeTypes,
};
